Add Windows compatibility to script
oddstr13/jellyfin-fixup-scripts pull request #2
Opened 2019-05-19 21:12 UTC by Pwnulatr

I took the liberty of adding compatibility for Windows since I saw that the original file was hardcoded to work with Linux.

2019-05-19 23:08 UTC, oddstr13 requested changes
In general, keep code style and formatting changes out of functional pull-requests, and follow the code style present in the existing code.

2019-05-19 23:08 UTC, oddstr13 commented on jellyfin-collection-fix.py
> +def is_running_linux():
I *strongly* disagree with this PEP8 convention.
Functions are `camelCase`. Classes are `PascalCase`. Variables are `snake_case`. Constants are `SNAKE_CAPS`.

2019-05-19 23:08 UTC, oddstr13 commented on jellyfin-collection-fix.py
> +    if sys.platform in ["win32", "cygwin"]:
This is missing msys2, I don't know exactly what the variable would be.

2019-05-19 23:08 UTC, oddstr13 commented on jellyfin-collection-fix.py
> +        DBFILE = input("WARNING: ENSURE THAT THE MEDIA SERVER IS SHUTDOWN BEFORE CONTINUING!\n"
This is a good place for a multiline string. Or multiple prints.
Separate the printed junk from the actual prompt.
Display the default to the user.

2019-05-19 23:08 UTC, oddstr13 commented on jellyfin-collection-fix.py
> +                       "\n\n> ") or os.environ['LOCALAPPDATA'] + r"\jellyfin"
`os.path.join()`. *Allways* use it when joining filesystem paths.

2019-05-19 23:08 UTC, oddstr13 commented on jellyfin-collection-fix.py
> +        print(f"ERROR: No write access to {DBFILE}")
Don't change coding style in a functional pull-request.
`str.format()` is perfectly fine.

2019-05-19 23:08 UTC, oddstr13 commented on jellyfin-collection-fix.py
> +              "directory")
There is *absolutely* no reason to split this string over multiple lines.
Entered path should also be verified where it is entered (`os.path.exists()`), and not rely on the write access check.

2019-05-19 23:08 UTC, oddstr13 commented on jellyfin-collection-fix.py
> +        print("Found database and R/W access is granted.")
I don't think this print is needed, as the script will exit otherwise.
Status updates before potentially long-running blocks of code are fine.

2019-05-19 23:08 UTC, oddstr13 commented on jellyfin-collection-fix.py
> +        res = cur.execute("SELECT tbi2.UserDataKey, tbi2.type, tbi2.ExtraIds FROM TypedBaseItems tbi1 INNER JOIN "
I get it, this line is long.
But that does not excuse the poor choice of where the lines are split, and this change does not improve code readability.

If anything, this should probably be a multiline constant somewhere near the beginning of the file.
(I'm assuming multiline strings would be fine for a single sqlite statement).

Either leave these lines alone, or format them to improve SQL readability.

2019-05-19 23:08 UTC, oddstr13 commented on jellyfin-collection-fix.py
> +                            {'eids': '|'.join(new_eids), 'guid': guid})
If you have to break up this line, use JSON style indented dictionary.
```python
..., {
    'eids': '|'.join(new_eids),
    'guid': guid,
})
```

2019-05-19 23:08 UTC, oddstr13 commented on jellyfin-collection-fix.py
> +            print(f"sudo -u {pwd.getpwuid(os.stat(DBFILE).st_uid).pw_name} {' '.join([sys.executable] + sys.argv)}")
eww, why is this even valid syntax?

2019-05-19 23:08 UTC, oddstr13 commented on jellyfin-collection-fix.py
> +        res = cur.execute("SELECT tbi2.guid, tbi2.ExtraType, tbi2.Name FROM TypedBaseItems tbi1 INNER JOIN "
See above.

2019-05-19 23:45 UTC, sparky8251 commented
If you can fix the style concerns and clean up the code as @oddstr13 has suggested we would be happy to accept this patch.

We just cannot accept patches that make scripts into odd hybrid styles and where possible we try to stick to the languages style.

2019-05-19 23:56 UTC, Pwnulatr commented on jellyfin-collection-fix.py
> +            print(f"sudo -u {pwd.getpwuid(os.stat(DBFILE).st_uid).pw_name} {' '.join([sys.executable] + sys.argv)}")
Are you referring to the import, the f string or both?

2019-05-20 00:00 UTC, oddstr13 commented on jellyfin-collection-fix.py
> +            print(f"sudo -u {pwd.getpwuid(os.stat(DBFILE).st_uid).pw_name} {' '.join([sys.executable] + sys.argv)}")
import is fine - pretty much standard way of doing platform-specific imports.

2019-05-20 00:13 UTC, oddstr13 commented
I hope this doesn't sound too harsh, but I'm leaning towards keeping this PR open as an issue, and implementing the changes myself when I can test it. Both because of all the unrelated changes in this PR, and because I'd want to test the changes before merging.
A way to detect running Jellyfin on Windows should really be implemented too, unless we can just fall back on Windows' tendency to lock all them files.

I'll probably be looking into setting up a Windows VM for testing this and other things this week.

Don't be too discouraged tho, as I'm happy to have issues pointed out, and suggestions of how to fix it / proper patches.
It's just that I'm not a fan of code style changes, unless there are *really* good reasons for it, and most if not all such changes in this PR are just noise in the diff.

2019-05-20 00:21 UTC, Pwnulatr commented
Fair enough. I'll revert the requested styling changes back to original and change those other things as requested. The implementation of detecting if Jellyfin is running on Windows is outside of my knowledge of Python, so that is my reasoning for not implementing it. I found solutions from various stackoverflow threads, but the majority of them were outdated or required third party libraries.

2019-05-21 20:43 UTC, oddstr13 approved these changes

2019-05-21 20:48 UTC, merged